### PR TITLE
Added automatic release

### PR DESCRIPTION
**Pull request by loeiten**
Creating a release will now also create a pip package on pypi.

In this PR
- Added the `.github` directory
- Modified `setup.py` like https://github.com/boutproject/boutdata/pull/23
- Modified `__init__.py` like https://github.com/boutproject/boutdata/pull/23
- Added GitHub secrets for this repository (although this is not reflected in this PR)

### CODE REVIEW

**Review by johnomotani — COMMENTED** [review]
Also (I think) needs the `pyproject.toml` file to tell `setuptools_scm` what to do. In https://github.com/boutproject/boutdata/pull/22 I also added `setuptools_scm` to `requirements.txt` to make sure it installs all the requirements for a dev install (`setuptools_scm` is a dependency when running from the repo rather than installing with pip/conda).

**Comment by loeiten** [comment]
Great catch @johnomotani 👍 
I've added the missing file and line in the latest commit.

**Review by johnomotani — COMMENTED** [review]
Oh sorry, I missed this the first time round: I think `__init__.py` needs updating too to set `__version__`.

**Comment by loeiten** [comment]
🤦 
So did I, thank you for spotting @johnomotani

**Review by johnomotani — APPROVED** [review]

**Pull request merged**
