### PR TITLE
Move the definition of all bout_types of BoutArray to BoutArray

### PR DESCRIPTION
**Pull request by dschwoerer**
That makes it easier to be consistent what types are supported.

Also add ArrayY and some others.

### CODE REVIEW

**Comment by dschwoerer** [comment]
It might be best to disable the scheduled jobs?

**Review by johnomotani — APPROVED** [review]
This looks like a sensible change to me.

Not sure why the CI actions aren't running - @ZedThree any idea?

**Comment by ZedThree** [comment]
I think the "expected" ones are actually old Travis ones we'd set to be explicitly required. The names don't seem to match the Github Actions, so I've removed them.

That doesn't explain why the Actions aren't running though... will investigate!

**Comment by ZedThree** [comment]
:shrug: I turned it off and on again and now it works

**Pull request merged**
